# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-07 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='details',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='park',
            name='dog_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
