# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_auto_20191107_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='park',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
