# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('tail', models.CharField(max_length=20)),
                ('fur_type', models.CharField(max_length=20)),
                ('weight', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lastupdate', models.DateTimeField()),
            ],
        ),
    ]
