# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-08 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='fur_type',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='tail',
        ),
    ]
