# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-08 07:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20191107_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='lastupdate',
        ),
        migrations.AddField(
            model_name='dog',
            name='lastupdated',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 1, 37, 10, 444491)),
        ),
    ]
