# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-08 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20191108_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='lastupdated',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 1, 44, 28, 563736)),
        ),
        migrations.AlterField(
            model_name='dog',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
